REPO_ROOT := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))

.PHONY: setup test format

setup:
	uv venv
	uv sync
	xcode-select --install || true
	@xcrun simctl list runtimes 2>/dev/null | grep -q com.apple.CoreSimulator.SimRuntime.iOS \
		|| xcodebuild -downloadPlatform iOS
	cp -n .env.example .env || true
	git config core.hooksPath .githooks
	@printf '%s\n' '# Generated by make setup — do not commit.' > .anvil-path.sh
	@printf '%s\n' '# Prepend this checkout to PATH so bare `anvil` works (same as ./anvil).' >> .anvil-path.sh
	@printf '%s\n' '# One-shot:  . ./.anvil-path.sh' >> .anvil-path.sh
	@printf '%s\n' "# Persistent: add to ~/.zshrc —  . '$(REPO_ROOT)/.anvil-path.sh'" >> .anvil-path.sh
	@printf '%s\n' 'export PATH="$(REPO_ROOT):$$PATH"' >> .anvil-path.sh
	@echo ''
	@echo 'Wrote .anvil-path.sh — run  . ./.anvil-path.sh  or add that source line to ~/.zshrc'

test:
	uv sync --group dev
	uv run pytest tests/ -v

format:
	uv sync --group dev
	uv run ruff format .
