"""CLI command to create task directories from GitHub PR URLs.

Given a single PR URL or a text file with one PR URL per line, generates
the full task directory structure under ``tasks/<repo_name>/``::

    tasks/<repo_name>/
    ├── metadata.yaml          (created or updated)
    ├── task-1/
    │   ├── task.md            (generated by LLM from PR description)
    │   ├── tests.swift        (generated by LLM from task + diff)
    │   ├── uitests.swift      (only when the task needs UI verification)
    │   └── solution.diff      (downloaded from GitHub)

Requires: ``gh`` CLI authenticated. ``OPENROUTER_API_KEY`` env var is optional —
without it, task.md falls back to the raw PR description and test files are left blank.
"""

from __future__ import annotations

import json
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Annotated, Optional

import typer

from .llm import DEFAULT_MODEL, call_llm, llm_available
from .prompts import REPO_MD_UPDATE_SYSTEM, TASK_MD_SYSTEM, TESTS_SYSTEM, UITESTS_SYSTEM

PR_URL_RE = re.compile(
    r"github\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+)/pull/(?P<number>\d+)",
    re.IGNORECASE,
)

GITHUB_PRS_DIR = Path(__file__).resolve().parent / "github_prs"


def parse_pr_url(url: str) -> tuple[str, str, int]:
    """Return *(owner/repo, repo_name, pr_number)*."""
    raw = url.strip()
    if not raw:
        raise ValueError("URL is empty")

    to_scan = raw if "://" in raw else f"https://{raw}"
    m = PR_URL_RE.search(to_scan) or PR_URL_RE.search(raw)
    if not m:
        raise ValueError(f"Expected https://github.com/owner/repo/pull/123, got: {raw}")

    owner, repo, num = m.group("owner"), m.group("repo"), int(m.group("number"))
    return f"{owner}/{repo}", repo, num


def _fetch_json(endpoint: str) -> dict:
    cmd = ["gh", "api", endpoint]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if proc.returncode != 0:
        msg = proc.stderr.strip() or proc.stdout.strip() or "unknown error"
        raise RuntimeError(f"gh api failed: {msg}")
    return json.loads(proc.stdout)


def _resolve_base_sha(full_repo: str, pr: dict) -> str:
    merge_sha = pr.get("merge_commit_sha")
    merged = pr.get("merged", False)
    if merged and merge_sha:
        commit = _fetch_json(f"/repos/{full_repo}/commits/{merge_sha}")
        parents = commit.get("parents", [])
        if parents:
            return parents[0]["sha"]
    return pr["base"]["sha"]


def _download_diff(diff_url: str, dest: Path) -> None:
    cmd = ["curl", "-sL", diff_url, "-o", str(dest)]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if proc.returncode != 0:
        raise RuntimeError(f"curl failed for {diff_url}: {proc.stderr.strip()}")


def _load_metadata(meta_path: Path) -> dict[str, str]:
    """Load existing ``metadata.yaml`` base_commits, or return empty dict."""
    if not meta_path.exists():
        return {}
    commits: dict[str, str] = {}
    for line in meta_path.read_text().splitlines():
        line = line.strip()
        if line.startswith("task-"):
            key, _, val = line.partition(":")
            commits[key.strip()] = val.strip()
    return commits


def _save_metadata(meta_path: Path, commits: dict[str, str]) -> None:
    lines = ["base_commits:"]
    for key in sorted(commits, key=lambda k: int(k.split("-")[1])):
        lines.append(f"  {key}: {commits[key]}")
    meta_path.write_text("\n".join(lines) + "\n")


def _next_task_number(out_dir: Path) -> int:
    """Find the next available task-N number."""
    existing = (
        [
            int(d.name.split("-")[1])
            for d in out_dir.iterdir()
            if d.is_dir()
            and d.name.startswith("task-")
            and d.name.split("-")[1].isdigit()
        ]
        if out_dir.exists()
        else []
    )
    return max(existing, default=0) + 1


def _generate_task_md(model: str, title: str, body: str, diff: str) -> str | None:
    user_msg = f"PR Title: {title}\n\nPR Description:\n{body}"
    if diff:
        diff_preview = diff[:80_000] if len(diff) > 80_000 else diff
        user_msg += f"\n\nSolution diff (for deriving API surface):\n{diff_preview}"
    return call_llm(model, TASK_MD_SYSTEM, user_msg)


def _generate_tests(model: str, task_md: str, diff: str, task_num: int) -> str | None:
    system = TESTS_SYSTEM.format(task_num=task_num)
    user_msg = f"task.md:\n{task_md}\n\nsolution.diff:\n{diff}"
    return call_llm(model, system, user_msg)


def _generate_uitests(model: str, task_md: str, diff: str, task_num: int) -> str | None:
    system = UITESTS_SYSTEM.format(task_num=task_num)
    user_msg = f"task.md:\n{task_md}\n\nsolution.diff:\n{diff}"
    result = call_llm(model, system, user_msg)
    if result and result.strip():
        return result
    return None


def _create_task(
    model: str,
    use_llm: bool,
    url: str,
    task_num: int,
    out_dir: Path,
) -> dict:
    """Create a single task directory.

    Returns a dict with keys: rc, task_dir_name, base_sha, title, url, issues.
    """
    tag = f"  [task-{task_num}]"
    task_label = f"task-{task_num}"
    issues: list[str] = []
    fail = {
        "rc": 1,
        "task_dir_name": None,
        "base_sha": None,
        "title": None,
        "url": url,
        "issues": issues,
    }
    try:
        full_repo, _, pr_number = parse_pr_url(url)
        pr = _fetch_json(f"/repos/{full_repo}/pulls/{pr_number}")
    except Exception as e:
        typer.secho(f"{tag} Error: {e}", fg=typer.colors.RED, err=True)
        issues.append(f"{task_label}: could not fetch PR — {e}")
        return fail

    task_dir_name = f"task-{task_num}"
    task_dir = out_dir / task_dir_name
    task_dir.mkdir(parents=True, exist_ok=True)

    title = pr.get("title", "Untitled")
    body = pr.get("body", "") or ""

    # 1. solution.diff — always download first
    diff_url = f"https://github.com/{full_repo}/pull/{pr_number}.diff"
    diff_dest = task_dir / "solution.diff"
    diff_content = ""
    diff_downloaded = False
    try:
        _download_diff(diff_url, diff_dest)
        diff_content = diff_dest.read_text(errors="replace")
        diff_downloaded = True
    except Exception as e:
        typer.secho(
            f"{tag} Warning: could not download diff: {e}",
            fg=typer.colors.YELLOW,
            err=True,
        )
        issues.append(f"{task_dir_name}: could not download solution.diff — {e}")
    if diff_downloaded and not diff_content.strip():
        issues.append(
            f"{task_dir_name}: solution.diff is empty — LLM output may be low quality"
        )

    # 2. task.md — try LLM, fall back to raw PR description
    typer.echo(f"{tag} Generating task.md...")
    task_md: str | None = None
    if use_llm:
        try:
            task_md = _generate_task_md(model, title, body, diff_content)
        except Exception as e:
            typer.secho(
                f"{tag} Warning: LLM task.md generation failed: {e}",
                fg=typer.colors.YELLOW,
                err=True,
            )
            issues.append(f"{task_dir_name}: task.md LLM generation failed — {e}")
    if not task_md:
        task_md = f"## {title}\n\n{body}"
        if use_llm:
            typer.secho(
                f"{tag} Falling back to raw PR description.",
                fg=typer.colors.YELLOW,
                err=True,
            )
            issues.append(
                f"{task_dir_name}: task.md fell back to raw PR description "
                "(LLM returned nothing)"
            )
        else:
            issues.append(
                f"{task_dir_name}: task.md written from raw PR only (no LLM configured)"
            )
    (task_dir / "task.md").write_text(task_md + "\n")

    # 3. tests.swift — try LLM, leave blank on failure
    typer.echo(f"{tag} Generating tests.swift...")
    tests: str | None = None
    if use_llm:
        try:
            tests = _generate_tests(model, task_md, diff_content, task_num)
        except Exception as e:
            typer.secho(
                f"{tag} Warning: LLM tests generation failed: {e}",
                fg=typer.colors.YELLOW,
                err=True,
            )
            issues.append(f"{task_dir_name}: tests.swift LLM generation failed — {e}")
    tests_body = tests + "\n" if tests else ""
    (task_dir / "tests.swift").write_text(tests_body)
    if not tests_body.strip():
        issues.append(f"{task_dir_name}: tests.swift is empty")

    # 4. uitests.swift — only written when LLM returns non-empty UI test code
    typer.echo(f"{tag} Generating uitests.swift...")
    uitests: str | None = None
    uitests_path = task_dir / "uitests.swift"
    if use_llm:
        try:
            uitests = _generate_uitests(model, task_md, diff_content, task_num)
        except Exception as e:
            typer.secho(
                f"{tag} Warning: LLM uitests generation failed: {e}",
                fg=typer.colors.YELLOW,
                err=True,
            )
            issues.append(f"{task_dir_name}: uitests.swift LLM generation failed — {e}")
    uitests_stripped = (uitests or "").strip()
    if uitests_stripped:
        uitests_path.write_text(uitests_stripped + "\n")
    elif uitests_path.exists():
        uitests_path.unlink()

    # 5. base commit
    base_sha: str | None = None
    try:
        base_sha = _resolve_base_sha(full_repo, pr)
    except Exception as e:
        typer.secho(
            f"{tag} Warning: could not resolve base commit: {e}",
            fg=typer.colors.YELLOW,
            err=True,
        )
        issues.append(f"{task_dir_name}: could not resolve base commit — {e}")
    else:
        if not base_sha:
            issues.append(
                f"{task_dir_name}: base commit is missing — "
                "not recorded in metadata.yaml"
            )

    typer.echo(f"{tag} Created (PR #{pr_number}: {title})")
    return {
        "rc": 0,
        "task_dir_name": task_dir_name,
        "base_sha": base_sha,
        "title": title,
        "url": url,
        "issues": issues,
    }


def _update_repo_md(
    model: str,
    use_llm: bool,
    out_dir: Path,
    tasks: list[dict],
    commits: dict[str, str],
) -> list[str]:
    """Update repo.md with newly created task entries. Returns human-readable issues."""
    issues: list[str] = []
    repo_md_path = out_dir / "repo.md"
    if not repo_md_path.exists():
        typer.echo("No repo.md found — skipping update.")
        issues.append("repo.md: file not found — skipped update")
        return issues

    existing = repo_md_path.read_text()

    # Build a summary of new tasks for the LLM
    task_lines = []
    for t in sorted(tasks, key=lambda t: t["task_dir_name"] or ""):
        base = commits.get(t["task_dir_name"], "unknown")
        task_lines.append(
            f"- {t['task_dir_name']}: title={t['title']}, url={t['url']}, base_commit={base}"
        )
    new_tasks_summary = "\n".join(task_lines)

    typer.echo("Updating repo.md...")
    if not use_llm:
        typer.echo("Skipped repo.md update (no LLM available).")
        issues.append(
            "repo.md: skipped update (no LLM API key — cannot rewrite Tasks section)"
        )
        return issues

    user_msg = f"Current repo.md:\n{existing}\n\nNew tasks to add:\n{new_tasks_summary}"
    updated: str | None = None
    try:
        updated = call_llm(model, REPO_MD_UPDATE_SYSTEM, user_msg)
    except Exception as e:
        typer.secho(
            f"Warning: LLM repo.md update failed: {e}",
            fg=typer.colors.YELLOW,
            err=True,
        )
        issues.append(f"repo.md: LLM update failed — {e}")
        return issues

    if updated and updated.strip():
        repo_md_path.write_text(updated.rstrip() + "\n")
        typer.echo(f"Updated {repo_md_path}")
    else:
        typer.echo("Skipped repo.md update (LLM returned empty).")
        issues.append("repo.md: LLM returned no content — file unchanged")

    return issues


def _read_url_file(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def _resolve_input(url_or_file: str) -> tuple[list[str], str | None]:
    """Return *(urls, repo_name_hint)*.

    Accepts a GitHub PR URL, a path to a text file, or a bare repo name
    that maps to ``commands/github_prs/<name>.txt``.
    """
    path = Path(url_or_file)
    if path.is_file():
        return _read_url_file(path), path.stem

    pr_file = GITHUB_PRS_DIR / f"{url_or_file}.txt"
    if pr_file.is_file():
        return _read_url_file(pr_file), url_or_file

    return [url_or_file], None


def create_tasks(
    url_or_file: Annotated[
        str,
        typer.Argument(
            help="Repo name (e.g. ACHNBrowserUI), PR URL, or path to a text file",
        ),
    ],
    output: Annotated[
        Optional[str],
        typer.Option(
            "--output", "-o", help="Output directory (default: tasks/<repo_name>)"
        ),
    ] = None,
    model: Annotated[
        str,
        typer.Option(
            "--model",
            "-m",
            help="LLM model for generation (litellm format, e.g. openrouter/anthropic/claude-sonnet-4-6-20250514)",
        ),
    ] = DEFAULT_MODEL,
) -> None:
    """Create task directories from GitHub PR URLs with AI-generated task descriptions and tests."""
    urls, repo_hint = _resolve_input(url_or_file)

    if not urls:
        typer.secho("No PR URLs found.", fg=typer.colors.RED, err=True)
        raise typer.Exit(1)

    # Check LLM availability
    use_llm = llm_available()
    if use_llm:
        typer.echo(f"Using model: {model}")
    else:
        typer.secho(
            "Warning: No API key found (OPENROUTER_API_KEY / ANTHROPIC_API_KEY / OPENAI_API_KEY) — "
            "task.md will use raw PR description, test files will be blank.",
            fg=typer.colors.YELLOW,
            err=True,
        )

    # Determine output directory
    if output:
        out_dir = Path(output)
    elif repo_hint:
        out_dir = Path("tasks") / repo_hint
    else:
        _, repo_name, _ = parse_pr_url(urls[0])
        out_dir = Path("tasks") / repo_name

    out_dir.mkdir(parents=True, exist_ok=True)
    typer.echo(f"Output directory: {out_dir}")

    # Load or init metadata
    meta_path = out_dir / "metadata.yaml"
    commits = _load_metadata(meta_path)

    # Create tasks (parallel, 3 at a time)
    start_num = _next_task_number(out_dir)
    rc = 0
    max_parallel = min(3, len(urls))

    def _run(i: int, url: str) -> dict:
        task_num = start_num + i
        typer.echo(f"\nTask {task_num}: {url}")
        return _create_task(model, use_llm, url, task_num, out_dir)

    created_tasks: list[dict] = []
    with ThreadPoolExecutor(max_workers=max_parallel) as pool:
        futures = {pool.submit(_run, i, url): i for i, url in enumerate(urls)}
        for future in as_completed(futures):
            result = future.result()
            rc |= result["rc"]
            created_tasks.append(result)
            if result["task_dir_name"] and result["base_sha"]:
                commits[result["task_dir_name"]] = result["base_sha"]

    # Save metadata
    _save_metadata(meta_path, commits)
    typer.echo(f"\nUpdated {meta_path}")

    # Update repo.md with new task entries
    summary_issues: list[str] = []
    for t in created_tasks:
        summary_issues.extend(t.get("issues") or [])
    successful_tasks = [t for t in created_tasks if t["rc"] == 0]
    if successful_tasks:
        summary_issues.extend(
            _update_repo_md(model, use_llm, out_dir, successful_tasks, commits)
        )

    typer.echo(f"Created {len(urls)} task(s) in {out_dir}")

    if summary_issues:
        typer.secho("\n--- Issues summary ---", fg=typer.colors.YELLOW, err=True)
        for line in summary_issues:
            typer.secho(f"  • {line}", err=True)

    if rc:
        raise typer.Exit(1)
