"""Create task directories from GitHub PR URLs.

Given a single PR URL or a text file with one PR URL per line, generates
the full task directory structure under ``tasks/<repo_name>/``::

    tasks/<repo_name>/
    ├── metadata.yaml          (created or updated)
    ├── task-1/
    │   ├── task.md            (generated by LLM from PR description)
    │   ├── tests.swift        (generated by LLM from task + diff)
    │   ├── uitests.swift      (generated by LLM from task + diff)
    │   └── solution.diff      (downloaded from GitHub)

Requires: ``gh`` CLI authenticated. ``OPENROUTER_API_KEY`` env var is optional —
without it, task.md falls back to the raw PR description and test files are left blank.
"""

from __future__ import annotations

import json
import os
import subprocess
import warnings
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Annotated, Optional

import typer

from .constants import DEFAULT_MODEL, GITHUB_PRS_DIR, PR_URL_RE
from .prompts import TASK_MD_SYSTEM, TESTS_SYSTEM, UITESTS_SYSTEM


def parse_pr_url(url: str) -> tuple[str, str, int]:
    """Return *(owner/repo, repo_name, pr_number)*."""
    raw = url.strip()
    if not raw:
        raise ValueError("URL is empty")

    to_scan = raw if "://" in raw else f"https://{raw}"
    m = PR_URL_RE.search(to_scan) or PR_URL_RE.search(raw)
    if not m:
        raise ValueError(f"Expected https://github.com/owner/repo/pull/123, got: {raw}")

    owner, repo, num = m.group("owner"), m.group("repo"), int(m.group("number"))
    return f"{owner}/{repo}", repo, num


def _fetch_json(endpoint: str) -> dict:
    cmd = ["gh", "api", endpoint]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if proc.returncode != 0:
        msg = proc.stderr.strip() or proc.stdout.strip() or "unknown error"
        raise RuntimeError(f"gh api failed: {msg}")
    return json.loads(proc.stdout)


def _resolve_base_sha(full_repo: str, pr: dict) -> str:
    merge_sha = pr.get("merge_commit_sha")
    merged = pr.get("merged", False)
    if merged and merge_sha:
        commit = _fetch_json(f"/repos/{full_repo}/commits/{merge_sha}")
        parents = commit.get("parents", [])
        if parents:
            return parents[0]["sha"]
    return pr["base"]["sha"]


def _download_diff(diff_url: str, dest: Path) -> None:
    cmd = ["curl", "-sL", diff_url, "-o", str(dest)]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if proc.returncode != 0:
        raise RuntimeError(f"curl failed for {diff_url}: {proc.stderr.strip()}")


def _load_metadata(meta_path: Path) -> dict[str, str]:
    """Load existing ``metadata.yaml`` base_commits, or return empty dict."""
    if not meta_path.exists():
        return {}
    commits: dict[str, str] = {}
    for line in meta_path.read_text().splitlines():
        line = line.strip()
        if line.startswith("task-"):
            key, _, val = line.partition(":")
            commits[key.strip()] = val.strip()
    return commits


def _save_metadata(meta_path: Path, commits: dict[str, str]) -> None:
    lines = ["base_commits:"]
    for key in sorted(commits, key=lambda k: int(k.split("-")[1])):
        lines.append(f"  {key}: {commits[key]}")
    meta_path.write_text("\n".join(lines) + "\n")


def _next_task_number(out_dir: Path) -> int:
    """Find the next available task-N number."""
    existing = (
        [
            int(d.name.split("-")[1])
            for d in out_dir.iterdir()
            if d.is_dir()
            and d.name.startswith("task-")
            and d.name.split("-")[1].isdigit()
        ]
        if out_dir.exists()
        else []
    )
    return max(existing, default=0) + 1


def _llm_available() -> bool:
    """Check if any LLM API key is configured."""
    return bool(
        os.environ.get("OPENROUTER_API_KEY")
        or os.environ.get("ANTHROPIC_API_KEY")
        or os.environ.get("OPENAI_API_KEY")
    )


def _strip_code_fences(text: str) -> str:
    """Remove markdown code fences if the LLM wraps its output in them."""
    stripped = text.strip()
    if stripped.startswith("```"):
        first_newline = stripped.index("\n") if "\n" in stripped else len(stripped)
        stripped = stripped[first_newline + 1 :]
    if stripped.endswith("```"):
        stripped = stripped[:-3]
    return stripped.strip()


warnings.filterwarnings("ignore", category=UserWarning, module="pydantic")


def _call_llm(model: str, system: str, user: str) -> str | None:
    """Send a prompt via litellm. Returns None if no API key is available."""
    if not _llm_available():
        return None
    import litellm

    resp = litellm.completion(
        model=model,
        max_tokens=8192,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    )
    text = resp.choices[0].message.content
    if not text:
        return None
    return _strip_code_fences(text)


def _generate_task_md(model: str, title: str, body: str, diff: str) -> str | None:
    user_msg = f"PR Title: {title}\n\nPR Description:\n{body}"
    if diff:
        diff_preview = diff[:80_000] if len(diff) > 80_000 else diff
        user_msg += f"\n\nSolution diff (for deriving API surface):\n{diff_preview}"
    return _call_llm(model, TASK_MD_SYSTEM, user_msg)


def _generate_tests(model: str, task_md: str, diff: str, task_num: int) -> str | None:
    system = TESTS_SYSTEM.format(task_num=task_num)
    user_msg = f"task.md:\n{task_md}\n\nsolution.diff:\n{diff}"
    return _call_llm(model, system, user_msg)


def _generate_uitests(model: str, task_md: str, diff: str, task_num: int) -> str | None:
    system = UITESTS_SYSTEM.format(task_num=task_num)
    user_msg = f"task.md:\n{task_md}\n\nsolution.diff:\n{diff}"
    result = _call_llm(model, system, user_msg)
    if result and result.strip():
        return result
    return None


def _create_task(
    model: str,
    use_llm: bool,
    url: str,
    task_num: int,
    out_dir: Path,
) -> tuple[int, str | None, str | None]:
    """Create a single task directory.

    Returns *(rc, task_dir_name, base_sha)* where rc is 0 on success.
    """
    tag = f"  [task-{task_num}]"
    try:
        full_repo, _, pr_number = parse_pr_url(url)
        pr = _fetch_json(f"/repos/{full_repo}/pulls/{pr_number}")
    except Exception as e:
        typer.secho(f"{tag} Error: {e}", fg=typer.colors.RED, err=True)
        return 1, None, None

    task_dir_name = f"task-{task_num}"
    task_dir = out_dir / task_dir_name
    task_dir.mkdir(parents=True, exist_ok=True)

    title = pr.get("title", "Untitled")
    body = pr.get("body", "") or ""

    # 1. solution.diff — always download first
    diff_url = f"https://github.com/{full_repo}/pull/{pr_number}.diff"
    diff_dest = task_dir / "solution.diff"
    diff_content = ""
    try:
        _download_diff(diff_url, diff_dest)
        diff_content = diff_dest.read_text(errors="replace")
    except Exception as e:
        typer.secho(
            f"{tag} Warning: could not download diff: {e}",
            fg=typer.colors.YELLOW,
            err=True,
        )

    # 2. task.md — try LLM, fall back to raw PR description
    typer.echo(f"{tag} Generating task.md...")
    task_md: str | None = None
    if use_llm:
        try:
            task_md = _generate_task_md(model, title, body, diff_content)
        except Exception as e:
            typer.secho(
                f"{tag} Warning: LLM task.md generation failed: {e}",
                fg=typer.colors.YELLOW,
                err=True,
            )
    if not task_md:
        task_md = f"## {title}\n\n{body}"
        if use_llm:
            typer.secho(
                f"{tag} Falling back to raw PR description.",
                fg=typer.colors.YELLOW,
                err=True,
            )
    (task_dir / "task.md").write_text(task_md + "\n")

    # 3. tests.swift — try LLM, leave blank on failure
    typer.echo(f"{tag} Generating tests.swift...")
    tests: str | None = None
    if use_llm:
        try:
            tests = _generate_tests(model, task_md, diff_content, task_num)
        except Exception as e:
            typer.secho(
                f"{tag} Warning: LLM tests generation failed: {e}",
                fg=typer.colors.YELLOW,
                err=True,
            )
    (task_dir / "tests.swift").write_text(tests + "\n" if tests else "")

    # 4. uitests.swift — try LLM, leave blank on failure
    typer.echo(f"{tag} Generating uitests.swift...")
    uitests: str | None = None
    if use_llm:
        try:
            uitests = _generate_uitests(model, task_md, diff_content, task_num)
        except Exception as e:
            typer.secho(
                f"{tag} Warning: LLM uitests generation failed: {e}",
                fg=typer.colors.YELLOW,
                err=True,
            )
    (task_dir / "uitests.swift").write_text(uitests + "\n" if uitests else "")

    # 5. base commit
    base_sha: str | None = None
    try:
        base_sha = _resolve_base_sha(full_repo, pr)
    except Exception as e:
        typer.secho(
            f"{tag} Warning: could not resolve base commit: {e}",
            fg=typer.colors.YELLOW,
            err=True,
        )

    typer.echo(f"{tag} Created (PR #{pr_number}: {title})")
    return 0, task_dir_name, base_sha




def _resolve_input(url_or_file: str) -> tuple[list[str], str | None]:
    """Return *(urls, repo_name_hint)*.

    Accepts a GitHub PR URL, a path to a text file, or a bare repo name
    that maps to ``wizard/github_prs/<name>.txt``.
    """
    # 1. Explicit file path
    path = Path(url_or_file)
    if path.is_file():
        return _read_url_file(path), path.stem

    # 2. Bare repo name → look up in github_prs/
    pr_file = GITHUB_PRS_DIR / f"{url_or_file}.txt"
    if pr_file.is_file():
        return _read_url_file(pr_file), url_or_file

    # 3. Single PR URL
    return [url_or_file], None


def _read_url_file(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def create_tasks(
    url_or_file: Annotated[
        str,
        typer.Argument(
            help="Repo name (e.g. ACHNBrowserUI), PR URL, or path to a text file",
        ),
    ],
    output: Annotated[
        Optional[str],
        typer.Option(
            "--output", "-o", help="Output directory (default: tasks/<repo_name>)"
        ),
    ] = None,
    model: Annotated[
        str,
        typer.Option(
            "--model",
            "-m",
            help="LLM model for generation (litellm format, e.g. openrouter/anthropic/claude-sonnet-4-6-20250514)",
        ),
    ] = DEFAULT_MODEL,
) -> None:
    """Create task directories from GitHub PR URLs with AI-generated task descriptions and tests."""
    urls, repo_hint = _resolve_input(url_or_file)

    if not urls:
        typer.secho("No PR URLs found.", fg=typer.colors.RED, err=True)
        raise typer.Exit(1)

    # Check LLM availability
    use_llm = _llm_available()
    if use_llm:
        typer.echo(f"Using model: {model}")
    else:
        typer.secho(
            "Warning: No API key found (OPENROUTER_API_KEY / ANTHROPIC_API_KEY / OPENAI_API_KEY) — "
            "task.md will use raw PR description, test files will be blank.",
            fg=typer.colors.YELLOW,
            err=True,
        )

    # Determine output directory
    if output:
        out_dir = Path(output)
    elif repo_hint:
        out_dir = Path("tasks") / repo_hint
    else:
        _, repo_name, _ = parse_pr_url(urls[0])
        out_dir = Path("tasks") / repo_name

    out_dir.mkdir(parents=True, exist_ok=True)
    typer.echo(f"Output directory: {out_dir}")

    # Load or init metadata
    meta_path = out_dir / "metadata.yaml"
    commits = _load_metadata(meta_path)

    # Create tasks (parallel, 3 at a time)
    start_num = _next_task_number(out_dir)
    rc = 0
    max_parallel = min(3, len(urls))

    def _run(i: int, url: str) -> tuple[int, str | None, str | None]:
        task_num = start_num + i
        typer.echo(f"\nTask {task_num}: {url}")
        return _create_task(model, use_llm, url, task_num, out_dir)

    with ThreadPoolExecutor(max_workers=max_parallel) as pool:
        futures = {
            pool.submit(_run, i, url): i for i, url in enumerate(urls)
        }
        for future in as_completed(futures):
            task_rc, task_dir_name, base_sha = future.result()
            rc |= task_rc
            if task_dir_name and base_sha:
                commits[task_dir_name] = base_sha

    # Save metadata
    _save_metadata(meta_path, commits)
    typer.echo(f"\nUpdated {meta_path}")
    typer.echo(f"Created {len(urls)} task(s) in {out_dir}")

    if rc:
        raise typer.Exit(1)
